### ISSUE TITLE
Kotlin Error on every first build my non-Kotlin based project

### ISSUE THREAD

**Issue by phunni** [BlueBoxWare/LibGDXPlugin#9]
Every time I build my project for the first time after starting Android Studio I get the following error:

```
Cannot add jps/kotlin-jps-plugin.jar from plugin 'Kotlin' to external compiler classpath: home directory of plugin not found
com.intellij.openapi.diagnostic.Logger$EmptyThrowable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:129)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.computeCompileServerPluginsClasspath(BuildProcessClasspathManager.java:109)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getStaticClasspath(BuildProcessClasspathManager.java:58)
	at com.intellij.compiler.server.impl.BuildProcessClasspathManager.getBuildProcessPluginsClasspath(BuildProcessClasspathManager.java:44)
	at com.intellij.compiler.server.BuildManager.launchBuildProcess(BuildManager.java:1154)
	at com.intellij.compiler.server.BuildManager.lambda$null$11(BuildManager.java:730)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Googling the error suggests that it's a problem with the Kotlin plugin, but they claim it's fixed and I'm using the latest version of both plugins.

I don't use Kotlin in my project - the only reason I have the plugin is to support your plugin, but I'm plagued with error messages every day...

**Comment by BlueBoxWare** [comment]
Can you try uninstalling the Kotlin plugin and then reinstalling it?

**Comment by BlueBoxWare** [comment]
No problem! I'm glad the problem is solved. If you encounter other issues, please let me know.
